id: I49F59DFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T06:33:31+00:00'
last_modified: '2022-06-07T14:15:17.797074+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4229
  title: རྗེ་སྒམ་པོ་པས་མཛད་པའི་ཏཻ་ལོ་ནཱ་རོའི་རྣམ་ཐར་སོགས་ཆོས་ཚན་ཁག་ཅིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B561:
      image_group_id: I1PD97374
      title: ''
      total_pages: 722
      order: 1
      base_file: B561.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
