id: P001739
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4229
  title: རྗེ་སྒམ་པོ་པས་མཛད་པའི་ཏཻ་ལོ་ནཱ་རོའི་རྣམ་ཐར་སོགས་ཆོས་ཚན་ཁག་ཅིག་
  author: ''
  volumes:
    d6b0909c163b454782274216a384db7a:
      image_group_id: I1PD97374
      title: ''
      volume_number: 1
      total_pages: 722
      base_file: v001.txt
